<footer>
				<p>Sitemap</p>
				<ul>
					<li><p>Article 1</p></li><!--
					--><li><a href="index.html">Home</a></li><!--
					--><li><a href="resourcesv2.html">Resources</a></li><!--
					--><li><a href="#">About</a></li>
				</ul>
				<ul>
					<li><p>Lectures</p></li><!--
					--><li><a href="lecturev2.html">Lecture Example</a></li><!--
					--><li><a href="#">Lecture 1</a></li><!--
					--><li><a href="#">Lecture 2</a></li><!--
					--><li><a href="#">Lecture 3</a></li><!--
					--><li><a href="#">Lecture 4</a></li>
				</ul>
				<ul>
					<li><p>Quizzes</p></li><!--
					--><li><a href="quizv2.html">Quiz 1</a></li><!--
					--><li><a href="#">Quiz 2</a></li><!--
					--><li><a href="#">Quiz 3</a></li>
				</ul>
				<p><br />Contact: <a href="#">Jeffrey Parker</a></p>
				<p><br /><a href="../homepage.html">Back to the homepage</a></p>
				<p><br />Copyright @ 2015 BCITCOMP 1950<br /><br /></p>
			</footer>