<nav  id="primary_nav_wrap">
			<ul>
				<li><p>Home</p>
					<ul>
						<li><a href="index.html">Home</a></li>
						<li><a href="resourcesv2.html">Resources</a></li>
						<li><a href="#">About</a></li>
					</ul>
				</li><!--
				--><li><p>Lectures</p>
					<ul>
						<li><a href="lecturev2.html">Lecture Example</a></li>
						<li><a href="#">Lecture 1</a></li>
						<li><a href="#">Lecture 2</a></li>
						<li><a href="#">Lecture 3</a></li>
						<li><a href="#">Lecture 4</a></li>	
					</ul>
				</li><!--
				--><li><p>Quizzes</p>
					<ul>
						<li><a href="quizv2.html">Quiz 1</a></li>
						<li><a href="#">Quiz 2</a></li>
						<li><a href="#">Quiz 3</a></li>
					</ul>
				</li>
			</ul>				
		</nav>